# Generated by Django 3.2.9 on 2023-08-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(default='', max_length=100)),
                ('product_details', models.CharField(default='', max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(default='', upload_to='pizzaapp/media')),
                ('product_publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=30)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
