# Generated by Django 3.2.9 on 2023-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_auto_20230823_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default='', max_length=100),
        ),
    ]
