# Generated by Django 3.2.9 on 2023-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=dict, max_length=100),
        ),
    ]
