# Generated by Django 3.2.9 on 2023-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_auto_20230825_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
